language: node_js
dist: trusty
sudo: required

node_js:
  - "14.4.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - echo "Removing unwanted files"
  - rm -vf _book/.travis.yml
  - rm -vf _book/*.yml
  - rm -vf _book/*.md
  - rm -vf _book/*.sh

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: _book
    target_branch: gh-pages
    on:
      branch: master

branches:
  only:
    - master

env:
 global:
   # Github Pages
   - GH_REF: github.com/RokidGlass/glass2-docs
   # Coding Pages
   - CO_REF: git@github.com:RokidGlass/glass2-docs.git
